In [1]:
#you will need your google API key!!!!!  it is in config under gkey for this file

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests
from pprint import pprint
from config import gkey
import time

In [2]:
#Import City CSV and Check file format
restaurant_df=pd.read_csv("inspection_data_2019.csv")
restaurant_df.head()

,address,aka_name,city,dba_name,facility_type,inspection_date,inspection_id,inspection_type,latitude,license_,...,eleventh_violation,twelf_violation,thirteenth_violation,fourteenth_violation,fifteenth_violation,sixteenth_violation,seventeenth_violation,eighteenth_violation,ninteeth_violation,twentieth_violation
0,3624 W WRIGHTWOOD AVE,NECESSARY & SUFFICIENT COFFEE,CHICAGO,NECESSARY & SUFFICIENT COFFEE,Restaurant,2019-09-17,2312415,License Re-Inspection,41.928352,2677227.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,311 S WACKER DR,SKY DINE 311,CHICAGO,JEWEL EVENTS CATERING,Restaurant,2019-09-17,2312410,License,41.877792,2670530.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1812-1814 W IRVING PARK RD,I-CAFE SUKUR'S PLACE,CHICAGO,I-CAFE SUKUR'S PLACE/PIDE VE LAHMACUN,Restaurant,2019-09-17,2312405,Canvass Re-Inspection,41.954318,2333622.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11601 W TOUHY AVE,MCDONALD'S (T3 HK FOOD COURT),CHICAGO,MCDONALD'S CORPORATION,Restaurant,2019-09-17,2312434,Canvass,42.008536,1140128.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2300 S THROOP ST,LA CHAPARRITA,CHICAGO,LA CHAPARRITA,Mobile Food Preparer,2019-09-17,2312417,License,41.850451,2689521.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
#****** FINAL TO USE *********
#Prepare Dataframe
places_df = pd.DataFrame([])

i = 0

#Run API Call
for index, row in restaurant_df.iterrows():
    item = row["aka_name"]
    lat = row["latitude"]
    lng = row["longitude"]
    location = f"{lat},{lng}"

    
    try:

        query=item+"&location"+location+"&radius=100"

        # Build URL and Generate Call
        url="https://maps.googleapis.com/maps/api/place/textsearch/json?query="+query+"&key="+gkey
        response_json = requests.get(url).json()
        #print(url)

        #Pull Data from Call and generate lists (**WE CAN ADD STUFF HERE**) 
        name = [item["name"] for item in response_json["results"]]
        rating = [item["rating"] for item in response_json["results"]]
        total_ratings = [item["user_ratings_total"] for item in response_json["results"]]
        address = response_json["results"][0]["formatted_address"]
        glat = response_json["results"][0]["geometry"]["location"]["lat"]
        glng = response_json["results"][0]["geometry"]["location"]["lng"]

        #Generate Initial DataFrame
        places_df = places_df.append(pd.DataFrame({"Data Name": row["aka_name"],
                                                   "Data License": row["license_"], 
                                                   "Data Address": row["address"],
                                                   "Data Lat": row["latitude"],
                                                   "Data Lng": row["longitude"],
                                                   "Google Name":name,
                                                   "User Rating":rating, 
                                                   "Total User Reviews": total_ratings,
                                                   "Google Address": address,
                                                   "Google Lat": glat,
                                                   "Google lng": glng}), ignore_index = True)

    except:
        print("not found " +str(row["aka_name"]))

    continue

not found MCDONALD'S  (T3 HK FOOD COURT)
not found OFRENDA, INC.
not found #1 DELI
not found SMOOTHIE JOINT
not found Edwards main and annex building
not found ALDI INC #64
not found BOLIVAR Y LINCOLN VENEZUELAN
not found I'M HUNGRY NOW!!, LLC
not found FOXGLOVE COFFEE
not found PANERA BREAD #1004
not found CHINKAY
not found nan
not found nan
not found SOUTHWEST SENIOR CENTER / GOLDEN DINER
not found ALDI INC #64
not found Starbucks Coffee#2229
not found THE LOTUS BLACK
not found nan
not found Carson (Old)
not found MIKKEYS 47 EXPRESS LLC
not found MANOLOS TAMALES, INC. #1
not found nan
not found EL CID TACOS #2
not found FOXGLOVE COFFEE
not found LATIN AMERICAN BAKERY
not found DOLLAR TREE #07725
not found BOLIVAR Y LINCOLN VENEZUELAN
not found FLIPPIN FLAVORS
not found nan
not found TOA TEA
not found TAQUERIA EL DORADO # 3
not found MIKKEYS 47 EXPRESS LLC
not found Wildwood
not found EL CHURRITO3
not found TIME MACHINE JUICE CO
not found EL CAMPEON TACO BAR EXPRESS
not found ALDI INC #64
not found CAFE #10
not found nan
not found STARBUCKS COFFEE #49695
not found STARBUCK'S COFFEE #2636
not found MOJO 33 NORTH LASALLE LLC
not found CREAMERIA LA ORDENA #1
not found LIL SAM
not found BIG STAR SHARKS
not found EL CAMPEON TACO BAR EXPRESS
not found ERWIN P. MCKENNIE, INC
not found nan
not found WINGSTOP #587
not found STEPPING STONES LEARINING INSTITUTION INC
not found ZAYN FOOD MART
not found Nepalese & Indian Cuisine
not found BURGER KING #10366
not found ESTHER'S ICE CREAM
not found FAMILY DOLLAR #32004
not found nan
not found ESTHER'S ICE CREAM
not found STARBUCKS COFFEE #2565
not found EVA'S CLUB
not found EMECHE CAKERY & CAFE
not found BON VIVANT CAKES LLC
not found nan
not found KONA ICE OF NILES
not found EL CHURRITO3
not found VAN BUREN & ASHLAND AMOCO
not found JEWEL FOOD STORE #3376
not found JOSEFINA'S NUTRITION
not found AFC SUSHI@JEWEL-OSCO #3376
not found JB HUNT CAFETERIA
not found MIKKEYS 47 EXPRESS LLC
not found KINGS  GYROS #2
not found HACHI SUSHI IN PETES MARKET
not found CAFE #10
not found ALDI FOODS #91
not found JEWEL FOOD STORE #3344
not found CARNICERIA GUANAJUATO #3
not found STORM ICE CREAM
not found FAMILY DOLLAR #32004
not found SALAD WORKS (T1 C18 FOOD COURT)
not found SALSA BORRACHA/MAMBO CLUB
not found WHITE CASTLE #26
not found JEWEL FOOD STORE #3344
not found nan
not found HALSTED SHELL, DUNKIN DONUTS, MR SUB
not found CHENGDU AROMA
not found NATURAL FOOD CATERING, CORP.
not found MCDONALD'S #490
not found LILY'S KWIK STOP
not found K G HALL
not found HALSTED SHELL, DUNKIN DONUTS, MR SUB
not found nan
not found I'M HUNGRY NOW!!, LLC
not found THE GARDEN OF HEAVEN CHILDCARE ACADEMY INC.
not found THE NEW MICDUCK'S DRIVE IN INC
not found TACONAZO EL ORIGINAL #1
not found ALDI FOODS #91
not found nan
not found MR QUILES MEXICAN FOOD #2
not found TAN LU
not found TACONAZO EL ORIGINAL #1
not found JONES ACADEMY, INCORPORATED
not found nan
not found PASSION HOUSE CAFE #3, LLC
not found nan
not found NATURAL FOOD CATERING, CORP.
not found FAMILY DOLLAR #5478
not found JCYS IRIS & STEVEN PODOLSKY FAMILY CENTER
not found STEPPING INTO THE FUTURE
not found nan
not found MANCHU WOK  (T3 ROTUNDA)
not found HOLY CROSS HOSPITAL/EMPLOYEE CAFETERIA
not found HOLY CROSS HOSPITAL/EMPLOYEE CAFETERIA
not found BRIOCHE DOREE  (T3/G/ROTUNDA)
not found ATINO'S PIZZA # 2 INC
not found COCHIAROS PIZZA #2
not found nan
not found STARBUCKS COFFEE #9942
not found FOOD LIFE/LETTUCE OFF PREM, CA
not found SANTORINI
not found HALSTED SHELL, DUNKIN DONUTS, MR SUB
not found HUDSON (T5 M12)
not found BRITISH AIRWAYS-1ST CLASS (T5-M12)
not found MEZQUITE EXPRESS # 2
not found nan
not found MAYA SUPERSTORE, INC.
not found CRAVE B2B, LLC
not found NATY'S PIZZA #2
not found WEATHERSEY WONDER WORLD INC
not found 7-ELEVEN #33732A
not found Cooked Chicago
not found MR QUILES MEXICAN FOOD #4
not found MR QUILES MEXICAN FOOD #2
not found FAMILY DOLLAR #5478
not found UNITED NOSHINS INC
not found TACONAZO EL ORIGINAL #1
not found HAROLD'S CHICKEN #88
not found PHLAVZ FOOD TRUCK
not found PEAR CHEF
not found PEAR CHEF
not found nan
not found WEATHERSEY WONDER WORLD INC
not found COCHIAROS PIZZA #2
not found MOUNSEF INTERNATIONAL
not found LOS COMALES #3
not found nan
not found CHINESE #1 KITCHEN
not found CHICAGO CAFE CATERERS
not found SUGAR BABY'S CAFE INCORPORATED
not found SUPERMERCADO EL GUERO #10 INC
not found EVA'S CLUB
not found LA FUENTA RESTAURANTE #2
not found Cooked Chicago
not found Cooked Chicago
not found AFC SUSHI @JEWEL-OSCO #3455
not found HUDSON NEWS T2 F8
not found FAMILY DOLLAR #32004
not found MIKEY B INC.
not found FAMILY DOLLAR #5478
not found nan
not found NIGHT FISHES
not found STARBUCKS COFFEE #13439
not found FIRST FACTORY FOODS
not found MANOLO'S TAMALES #3
not found HAROLD'S CHICKEN SHACK #52
not found nan
not found STARBUCKS COFFEE #2527
not found STARBUCKS COFFEE #228
not found STARBUCKS COFFEE #228
not found PRIME NOW LLC
not found SUPERMERCADO EL GUERO #10 INC
not found TALARD THAI MARKET
not found PONCITLAN #5
not found PRIME NOW LLC
not found AFC SUSHI @ WALGREENS
not found WALGREENS #1298
not found STARBUCKS COFFEE #49431
not found FAMILY DOLLAR #32004
not found JEWEL FOOD STORE #3501
not found TIME MACHINE JUICE CO
not found MUSE SPIRITS
not found JEWEL FOOD STORE #3455
not found JOHN + PAT ANDERSON'S CAFE
not found MOBIL/MICHOACANA
not found nan
not found WALGREENS #1298
not found STARBUCKS COFFEE #228
not found HAROLD'S CHICKEN SHACK #52
not found AFC SUSHI@JEWEL-OSCO #3442
not found MANOLO'S TAMALES #3
not found FAMILY DOLLAR #32004
not found STARBUCKS COFFEE #228
not found McDONALD'S  (T2  E/F)
not found AUNTIE ANNE'S PRETZELS  (T1-C17)
not found HUDSON NEWS   (T1-C18)
not found CHURCH'S CHICKEN # 483
not found HUDSON NEW T1 C 22
not found WALGREENS #03395
not found LOS MANGOS NEVERIA Y FRUTERIA #3
not found nan
not found FANNIE MAY SUITE/CREE LIGHTING CLUB/SUITE PANTRIES
not found JEWEL FOOD STORE #3477
not found BLUE MOUSE HOLDINGS, LLC
not found BRIOCHE DOREE  (T1-C20)
not found BLUE MOUSE HOLDINGS, LLC
not found TALARD THAI MARKET
not found THE LOTUS BLACK
not found SANTORINI
not found LA MICHOACANA Y EL SURTIDAZO BOTANERO
not found #1 CHOP SUEY
not found MANOLO'S TAMALES #3
not found JEWEL FOOD STORE #3234
not found CHILDREN'S HOLISTIC INTEGRATED LEARNING AND DEVELO
not found THE LOTUS BLACK
not found CARNICERIA GUANJUATO #3
not found McDONALD'S  (T2  E/F)
not found Mc DONALD'S  (T3  L4)
not found PHILIPPINE PLAZA/ORGINAL BAKER'S DELIGHT CARRYOUT
not found McDONALDS (T1 C10)
not found McDONALD'S  (T1  B11)
not found FRESH MARKET ON THE GO (T1  C23)
not found PIEROGI SQUAD
not found LEON'S BAR-B-QUE-#4
not found JEWEL FOOD STORE #3043
not found STARBUCKS COFFEE #2410
not found AZIZ CAFE
not found JEWEL FOOD STORE #3477
not found PIEROGI SQUAD
not found PIZZERIA LO SPIZZICO
not found Harold's Chicken #36
not found TAQUERIA EL ASADERO #1
not found MIRCH INCORPORATED
not found HUDSON NEWS  (T1-B14)
not found CLEO'S
not found nan
not found PONCITLAN #5
not found WHITE CASTLE #23
not found JEWEL FOOD STORE #3296
not found CHAVELO'S TACOS, INC.
not found CHIPOTLE MEXICAN GRILL #2923
not found LOS MANGOS NEVERIA Y FRUTERIA #3
not found CARNICERIA GUANJUATO #3
not found LOS TACOS BOYS #1
not found PALETERIA AZTECA #2
not found nan
not found CHECKERS #6361
not found MIRCH INCORPORATED
not found HUDSON NEWS  (T1-B14)
not found LAS TRES CAMPANITAS #7
not found NORTH GARDEN
not found CIBO EXPRESS GOURMET MARKET #2 T2 Vendor Checkpoin
not found SKYSCRAPERS (T3  K10)
not found AZIZ CAFE
not found BUSCIA'S
not found OASIS FRESH FOOD INC.
not found PI18EN
not found AJAJA FOODS
not found PIZZERIA LO SPIZZICO
not found PLZEN
not found LEGHORN CHICKEN
not found RUSH STREET (T3/H14)
not found Auntie Anne's Pretzels (T2  E/F)
not found CHECKERS #6361
not found CNN (T3-H5)
not found JEANNIES FLAN INC.
not found HUDSON NEWS  T-1 GATE B5
not found EXCLUSION FOOD MARKET
not found KIKKA- KINGSBURY
not found WING STOP # 894
not found PEAR CHEF
not found PEAR CHEF
not found HACIENDA LA AMISTAD
not found DOUBLE HEADER BAR & GRILL
not found PHILIPPINE PLAZA/ORGINAL BAKER'S DELIGHT CARRYOUT
not found STEPPING STONES LEARINING INSTITUTION INC

not found STARBUCKS  T3 L20
not found DOUBLE HEADER BAR & GRILL
not found CLEO'S
not found KEXIN RESTAURANT
not found MARIANO'S #8527 UKRANIAN VILLAGE
not found UNIVERSITY OF CHICAGO BOOKSTORE # 491
not found JEWEL FOOD STORE #3092
not found AUSTIN OASIS HEALTH CARE
not found DA PIZZA DUDE
not found SUGAR BABY'S CAFE INCORPORATED
not found BEST START/ERA THOMPSON, INC.
not found DONI DESSERT AND PASTRY
not found MI MONTANA
not found DUNKIN' DONUTS/JET BOX
not found PORKCHOP/ BIG & LITTLE'S
not found GALILEO BAR (T1-B22)
not found TALARD THAI MARKET
not found STARBUCKS COFFEE (T1-B14)
not found ROOM SERVICE-MINI BARS
not found MIKEY B INC.
not found SAORY RESTAURANT, INC
not found DOOM STREET EATS/PUFFS OF DOOM/PAPA LUKE'S GRAVY B
not found EL PROGRESO
not found JEWEL FOOD STORE #3454
not found HUDSON (T5 MAIN/M10 DEPARTURES)
not found SUPERMERCADO CHAPULTEPEC #2
not found SIX O SIX THE LOUNGE
not found MCDONALDS #27672
not found LINDO MICHOACAN/RESTAURANT VIVA MEXICO
not found PINATAS FANY
not found BEST SUBS #3
not found KOFE  (T5/M-8/DEPARTURE/POST SECURITY
not found LOS ARRIADOS
not found FOOD 4 LESS MIDWEST #789
not found AIR FRANCE (T5-M7)
not found HUDSON NEWS (T5 DEPARTURE) M14
not found STARBUCKS COFFEE#2261
not found THESE WINGZ
not found PHILIPPINE PLAZA/ORGINAL BAKER'S DELIGHT CARRYOUT
not found 1 S WACKER
not found TRATTORIA #10
not found PALETERIA Y NEVERIA DELICIAS TROPICALES
not found TACONAZO EL ORIGINAL #1
not found FAMILY DOLLAR STORE #7156
not found JAYMAY RESTAURANT
not found THE QUARRY EVENT CENTER/GEODE RESTAURANT
not found ROSELAND SLF ASSOCIATES LP
not found ACAPULCO  BAKERY #2
not found KOFE  (T5/M-8/DEPARTURE/POST SECURITY
not found 7-ELEVEN #33920A
not found FOOD LIFE/LETTUCE OFF PREM, CA
not found WENDY'S #001110
not found nan
not found EMPLOYEES CAFETERIA
not found POTBELLY SANDWICH WORKS # 114
not found BEST START/ERA THOMPSON, INC.
not found NICKS PIT STOP #2
not found WHITE CASTLE #49
not found CHURCH'S CHICKEN # 982
not found SEE THRU CHINESE KITCHEN #21
not found RAYMONDS TACOS # 3
not found BURGER KING #207
not found UNITED EMPLOYEE CAFETERIA (T1-C MID LEVEL)
not found STARBUCKS COFFEE #2949
not found Eurest Dining Services @ Quaker Oats
not found PALETERIA COCKTAILS TROPICALES
not found SAN MIGUEL RESTAURANT COMIDA AUTENTICA MEXICANA
not found TATTLER POST #973 AMER. LEGION
not found BURGER KING #17392
not found DDANDAVIS FOOD MART
not found 2451 MART
not found PINATAS FANY
not found BUSOFAT AFRICAN CUISINE
not found MARIANO'S FRESH MARKET #8507
not found RAYMONDS TACOS # 3
not found COLD STONE CREAMRY #23263
not found DOLLAR TREE #06910
not found EL CHUBASCO
not found TRASPASADA #2
not found JEWEL FOOD STORE #3234
not found TACONAZO EL ORIGINAL #1
not found AFC SUSHI @ Jewel Osco #3234
not found STEAKKNIFE
not found STARBUCKS COFFEE#2261
not found WICKER BASKET MARKET
not found WHADDA JERK, LLC
not found LA COCINITA FOOD TRUCK CHICAGO
not found nan
not found nan
not found THE FIELD BISTRO/CATERING EAST & WEST
not found BURGER KING #22995
not found WENDY'S #001110
not found DAMATO BAKERY #1
not found OASIS FRESH FOOD INC.
not found nan
not found STARBUCKS COFFEE #11751
not found EFIE'S CANTEEN (TAXI/LIMO AREA)
not found STROGER CAFE
not found STARBUCKS  (T3 H2)
not found STARBUCKS COFFEE #2334
not found JEWEL FOOD STORE #3030
not found SUPERMERCADO EL PARAISO INC.
not found EL POLLO CRIS CRIS #3
not found TOMMY WEST SIDE FOOD MART
not found nan
not found 7-ELEVEN #33920A
not found DOLLAR TREE #06910
not found 4 YOLKS
not found THE TEA POST
not found BRIOCHE DOREE CAFE (T1-B DEPARTURE)
not found UNITED EMPLOYEE CAFETERIA (T1-C MID LEVEL)
not found SIX O SIX THE LOUNGE
not found SUPERMERCADO LA CHIQUITA #4
not found ES LA HORA DEL CHIVO
not found RAYMONDS TACOS # 3
not found KITA-O
not found EL POLLO CRIS CRIS #3
not found DOLLAR TREE #06910
not found MILLIE'S HOUSE KEDZIE
not found MCDONALDS  (T3  K9)
not found OASIS FRESH FOOD INC.
not found nan
not found LA FAMILIA DOLLAR PLUS
not found FRESH TO GO (MAIN FLOOR)
not found CHILI'S  TOO (T3-H2)
not found DAMATO BAKERY #1
not found MELLO'S CARRY OUTS
not found DATING DUCK FOOD
not found LAS TRES CAMPANITAS INC #2
not found Eurest Dining Services @ Safer Foundation
not found STARBUCK'S (T2 E9)
not found STARBUCKS COFFEE #2639
not found AFC SUSHI@JEWEL-OSCO #3241
not found TATTLER POST #973 AMER. LEGION
not found nan
not found BURGER KING #22995
not found nan
not found X CENTERLIN ADULT DAYCARE
not found DOUBLE HEADER BAR & GRILL
not found CHEF GRADY,LLC
not found TAQUERIA ATOTONILCO #1
not found nan
not found nan
not found ARGO TEA (T3-L Near Lotto and TSA)
not found JEWEL FOOD STORE #3241
not found GEO.  NOTTOLI & SON
not found TSIRONIS LLC
not found nan
not found AUNT PATTY'S COFFEE SHOP
not found AMERICAN GLORY FOOD TRUCK
not found JEWEL FOOD STORE #3296
not found STARBUCKS COFFEE #2639
not found THE FIELD BISTRO/CATERING EAST & WEST
not found MELLO'S CARRY OUTS
not found 7-ELEVEN #33758 C
not found STARBUCKS COFFEE #10905
not found JEWEL FOOD STORE #3368
not found Collaboration Cafe
not found COASTLINE CATERING
not found HOMESTYLE TASTE
not found PALETERIA Y NEVERIA LA MICHOACANA FRESA
not found LA QUEBRADA #5
not found MARISCO EL VENENO #2 CORP.
not found LOGAN'S
not found HOMESTYLE TASTE
not found BARNES & NOBLE BOOKSELLERS#2922
not found LA FAMILIA DOLLAR PLUS
not found THE TEA POST
not found POLARIS CLUB (T1-C18)
not found LAS GORDITAS DEL NIETO DE DON ANGEL INC.
not found FISHER APARTMENT (GOLDEN DINER)
not found GORDITAS MARIA INC.
not found NUMERO UNO SUPER MERCADO
not found NLU CAFETERIA
not found EXTREMA NUTRICION
not found nan
not found MIKEE'S 1-2-3, INC.
not found DI DI RAMINOV SHOW
not found THE FIELD BISTRO/CATERING EAST & WEST
not found JEWEL FOOD STORE #3181
not found LA MICHOACANA CHASCAHELADOS INC.
not found MOROLEON FOODS #2
not found BURGER KING #7623
not found PALETERIA Y NEVERIA LA MICHOACANA FRESA
not found COLES SLF, LLC
not found CHELIS COCINA ECONOMICA, INC.
not found LOGAN'S
not found THE GROVE/ SMOOTHIE KING  (T1  B6)
not found BARNES & NOBLE BOOKSELLERS#2922
not found MEZQUITE EXPRESS # 2
not found CYNTHIA'S GUMBO EXPRESS
not found TAMALES EMMA LA CHAPARRITA
not found CLUB NUTRICION LIA
not found PUBLIC CLOSEOUT #3
not found 7-ELEVEN #38183B
not found JEWEL FOOD STORE #3501
not found AFC SUSHI @ JEWEL-OSCO #3501
not found ROSA TAMALES #4
not found JOYFUL STEPS LEARNING CENTER LLC
not found 7-ELEVEN #38183B
not found TOCCO (T5 M-07)
not found URBAN OLIVE/T5 M10
not found RJ GRUNTS/T5 M10
not found HUB 51/T5 M10
not found BRITISH AIRWAYS-FIRST LOUNGE (T5-M11)
not found STARBUCKS  (T1  C-07)
not found DDANDAVIS FOOD MART
not found KABAB GRILL
not found GOOSE ISLAND (T1  C10)
not found VIENNA BEEF/PIZZERIA UNO (T1 C6)
not found MS. TITTLE'S CUPCAKES
not found GORDITAS LOLI'S #2
not found STARBUCKS COFFEE #2639
not found RASMIAH FOOD
not found REBECCA K. CROWN CHLD. DEV. CT
not found MOROLEON FOODS #2
not found SIX O SIX THE LOUNGE
not found STARBUCKS COFFEE #2252
not found JEWEL FOOD STORE #3181
not found T- TIME NUTRITION
not found JULIA'S L'AFRIQ CUIZINE
not found BARNES & NOBLES BOOKSELLERS #2780
not found 7-ELEVEN #26878 F
not found ROSA TAMALES #4
not found FIRST STEPS TO SUCCESS
not found THIRD STAR/SIXES & EIGHTS/MAIN KITCHEN
not found CLUB NUTRICION LIA
not found PANDA EXPRESS #1345
not found TACOS DEL RIO INC.
not found DI DI RAMINOV SHOW
not found LA V BAKERY, INC
not found Columbus
not found GOLDEN SPICE BAKERY
not found BAR LORRAININE'S
not found ARAMI/WOODGRAIN
not found EL CAMPESTRE #2
not found 7-ELEVEN #26878 F
not found DENNIS'S CARRY OUT
not found MCDONALD'S  (T3 HK FOOD COURT)
not found TOCCO (T5 M-07)
not found ADRIANNE'S CATERING LLC
not found KITCHENETTE CORPORATION
not found FRUIT GOD
not found FRUIT GOD INC
not found BLUE SPOT SUSHI CORP.
not found nan
not found ARAMARK @ INFORMATION RESOURCES
not found CYNTHIA'S GUMBO EXPRESS
not found nan
not found FIVE SQUARED FOOD TRUCK
not found SMOKE FILLED ROOM
not found FIRST STEPS TO SUCCESS
not found nan
not found nan
not found nan
not found JEWEL FOOD STORE #3176
not found nan
not found LAILA'S GRAND GAME ROOM INC
not found HAROLD'S CHICKEN #55
not found nan
not found David Jenson - Personal Chef, Ltd

not found DENNIS'S CARRY OUT
not found DDANDAVIS FOOD MART
not found LOQUACIOUS CULINARY EVENTS, INC
not found LA FORTALEZA DE ARCELIA GUERRERO
not found TACONAZO EL ORIGINAL #1
not found ADRIANNE'S CATERING LLC
not found EL POLLO CRIS CRIS #3
not found THEODORE HERZL ELEMENTARY SCHOOL/FRAZIER  CHARTER
not found CYNTHIA'S GUMBO EXPRESS
not found BURGER KING #2654
not found SUPER STAR & GYROS # 2
not found AFC SUSHI @ JEWEL OSCO #3224
not found JOHN SCHALLER
not found TAQUERIA SAN JOSE #1
not found MCDONALD'S  (T3 HK FOOD COURT)
not found BANGE'S
not found HAROLDS CHICKEN #55
not found LAILA'S GRAND GAME ROOM INC
not found MIKEE'S 1-2-3, INC.
not found nan
not found JEWEL FOOD STORE #3176
not found LOS COMALES #3
not found GOURMET JUNK FOOD
not found BANGE'S
not found SEAFOOD JUNCTION # 4 INC.
not found DONI DESSERT AND PASTRY
not found CLEO'S SOUTHERN CUISINE
not found RAYMONDS TACOS #1
not found MANOLOS TAMALES, INC. #2
not found CYNTHIA'S GUMBO EXPRESS
not found PRIME TIME SNACKS
not found TACOS MARIO'S LIMITED
not found JEWEL FOOD STORE #3442
not found THORNDALE WEST CAFE #1
not found FOOD 4 LESS MIDWEST #789
not found nan
not found BRO-N-LAWS BAR-B-Q
not found WOLFGANG PUCK (T1 B7)
not found GOURMET GORILLA
not found QUESADILLAS Y HUARACHES JUMBO
not found STARBUCKS COFFEE #2479
not found #1 CHOP SUEY
not found DUNKIN DONUTS (T3 HK FOODCOURT)
not found MI LINDO MEXICO MARKET, LLC
not found STARBUCKS HK APEX (T3 HK FOODCOURT)
not found TACO AND BURRITO EXPRESS #3
not found DDANDAVIS FOOD MART
not found STARBUCKS (T3  G14 LL)
not found BAR-B-QUE KINGDOM
not found BOWLS/ CARB FREE CAFE
not found Starbucks Coffee #233
not found MILLION FLAVOR, INC
not found EL CASTILLO SUPERMERCADO CARNICERIA FRUITERIA
not found nan
not found RAYMONDS TACOS #1
not found GT MARGIES  MAXWELL STREET POLISH
not found TACO AND BURRITO EXPRESS #3
not found MARIANO'S #8516
not found KIRKLAND & ELLIS
not found HOMESTYLE TASTE
not found PORKCHOP/ BIG & LITTLE'S
not found WHITE CASTLE #61
not found HVAC PUB/GLACIER CITY FROZEN YOGURT
not found EL GRAN BURRITO EXPRESS #2
not found FOOD 4 LESS MIDWEST #789
not found TCBY/JUICE WORKS (T3 ROTUNDA)
not found SUBWAY (T3 ROTUNDA)
not found MANCHU WOK  (T3 ROTUNDA)
not found CONNECT THRU CHICAGO (T2 GATE F1)
not found Chicagoland Deli International
not found CHILI'S TOO (T3 G9)
not found CHURCH'S CHICKEN # 982
not found TACO AND BURRITO EXPRESS #3
not found TACO AND BURRITO EXPRESS #3
not found Walgreens # 05356
not found nan
not found Starbucks Coffee #233
not found HUDSON (T2 UNITED MAIN)
not found STARBUCKS COFFEE #233
not found GOOSE ISLAND CHICAGO (T3/L10)
not found CAFETERIA Y NEVERIA JIMENEZ
not found WHITE CASTLE #25
not found THE QUARRY EVENT CENTER/GEODE RESTAURANT
not found MACARONI GRILL (T3-K2)
not found CHINELAS
not found BURGER KING #2654
not found CAFETERIA Y NEVERIA JIMENEZ
not found CHILI'S TOO (T2  F4)
not found nan
not found MILLION FLAVOR, INC
not found THEODORE HERZL ELEMENTARY SCHOOL/FRAZIER  CHARTER
not found nan
not found UPLIFT Community AT ARAI
not found AFC SUSHI @ JEWEL OSCO # 2940
not found JEWEL FOOD STORE #3441
not found Sherman
not found MELLOS CARRY OUTS
not found MELLO'S CARRY OUTS
not found BIRRIERIA Y TAQUERIZ LOPEZ #2
not found WHITE CASTLE #23
not found CHIPOTLE MEXICAN GRILL #2923
not found THE 3RD COAST
not found GOURMET GORILLA
not found CHINELAS
not found ICE BAR (T3 L2)
not found STARBUCKS/T3 L3
not found JAMES WELDON JOHNSON  CPC
not found GOOSE ISLAND CHICAGO (T3/L10)
not found THE QUARRY EVENT CENTER/GEODE RESTAURANT
not found MELLOS CARRY OUTS
not found BRIOCHE DOREE CAFE BAKERY (T3 K15 FOOD COURT)
not found BJ'S MARKET (T3 K15 FOOD COURT)
not found MELLO'S CARRY OUTS
not found SABORES DE AMERICA, KATAKANA KOKO MEXICAN GRILL
not found CHURCH'S CHICKEN # 982
not found PLATO LEARNING ACADEMY # 2
not found WHITE CASTLE #24
not found TACO BELL #30407
not found HUDSON NEW T3 G19
not found MACARONI GRILL (T3-K2)
not found SUPERMERCADO EL GUERO #10 INC
not found SUBWAY #3333
not found HERMAN HALL
not found A 87  CAFE AND RESTAURANT,CORP
not found FAMILY DOLLAR STORE #7570
not found Taqueria El Dorado #2
not found FUN OL' CAKES INC.
not found BOSTON MARKET #825
not found Eurest Dining Services @ USG
not found nan
not found HILTON O'HARE/ANDIAMO'S/CAFFE MERCATO
not found HILTON O'HARE/ANDIAMO'S/CAFFE MERCATO
not found WAHMEI FOOD CORP
not found Eurest Dining Services @ USG
not found HILTON O'HARE/ANDIAMO'S/CAFFE MERCATO
not found FAMILY DOLLAR #5630
not found JEWEL FOOD STORE #3114
not found HILTON O'HARE/ANDIAMO'S/CAFFE MERCATO
not found HILTON O'HARE/ANDIAMO'S/CAFFE MERCATO
not found ARTEMIO'S BAKERY #2
not found BOUEFGHAUS
not found HILTON O'HARE/ANDIAMO'S/CAFFE MERCATO
not found HILTON O'HARE/ANDIAMO'S/CAFFE MERCATO
not found HILTON O'HARE/ANDIAMO'S/CAFFE MERCATO
not found nan
not found THE LITTLE CORNER SNACK SHOP
not found HILTON O'HARE/ANDIAMO'S/CAFFE MERCATO
not found SHOP & SAVE  MARKET #2100
not found AMERICAN AIRLINES (T3-G8)
not found HILTON O'HARE/ANDIAMO'S/CAFFE MERCATO
not found TAQUERIA OCHOA'S #2
not found JIE SNACK HOUSE INC.
not found CLEO'S SOUTHERN CUISINE
not found ROOM FIVE HUNDRED
not found CARNICERIA LA VILLA #2
not found STARBUCKS COFFEE #2515
not found JIE SNACK HOUSE INC.
not found nan
not found ROBINSON'S #1 RIB
not found MAIN BUILDING/ANNEX
not found LUELLA'S GOSPEL BIRD
not found Pullman
not found KIKKA-SOUTH LOOP
not found MEZQUITE EXPRESS # 2
not found Cullen
not found nan
not found nan
not found THIRD STAR/SIXES & EIGHTS/MAIN KITCHEN
not found A 87  CAFE AND RESTAURANT,CORP
not found nan
not found EASY SNACK
not found MORELIA SUPERMARKET #2
not found LUELLA'S GOSPEL BIRD
not found EMECHE CAKERY & CAFE
not found FAMILY DOLLAR #5630
not found IDA B WELLS
not found SANDARBAN'S FISH BAZAAR
not found DANIEL S. WENTWORTH ANNEX
not found ZARIVA FOOD MART
not found WAHMEI FOOD CORP
not found ASIAN CHOPSTICKS, INC
not found JOHN + PAT ANDERSON'S CAFE
not found Skinner Branch (Sousa)
not found MAC One Midway LLC./PREMIER CATERING & EVENTS, LLC
not found YMCA GARFILED FAMILY DEVELOPMENT CENTER
not found EASY SNACK
not found JEWEL FOOD  STORE # 3345
not found MEZQUITE EXPRESS # 2
not found W2005 CMK REALTY, L.L.C.
not found JEWEL FOOD STORE #3470
not found Cooked Chicago
not found SANDARBAN'S FISH BAZAAR
not found DANIEL S. WENTWORTH ANNEX
not found JEWEL FOOD STORE #3302
not found MAIN KITCHEN, EMPLOYEES CAFETERIA
not found ERNESTO GROCERY
not found DART/ARAMARK EMPLOYEE CAFETERIA
not found SUPERMERCADO MI LUPITA
not found THE CONGRESS HOTEL(TAVERN HALL-RAFAEL)
not found EMPLOYEE'S CAFETERIA
not found LUELLA'S GOSPEL BIRD
not found TAMALESY RESTAURANT COSTA GRANDE
not found HERITAGE 1201 W LAKE LLC
not found Seward
not found 7 ELEVEN #33726A
not found SANDARBAN'S FISH BAZAAR
not found MAIN KITCHEN / GREAT
not found FAMILY DOLLAR # 4666
not found 7-ELEVEN #33496C
not found EXPRESS CARRY - OUT INC
not found CICERO & MONTROSE SHELL
not found TONY'S  KITCHEN #2 INC.
not found Skinner Branch (Sousa)
not found nan
not found POLONIA
not found MAIN KITCHEN/ROOM SERVICE
not found Brighton Park
not found W2005 CMK REALTY, L.L.C.
not found PANDA EXPRESS # 1370
not found T JOELS FAMILY RESTAURANT
not found KOULOU INC.
not found BARNARD
not found MAIN KITCHEN,FOOD COURT,WAREHOUSE,CAFE A-1, A-2
not found LOS OLIVO'S
not found EL TACO SABROSO #1 INC
not found CRAVE B2B, LLC
not found BRIGHT BEAUTIFUL BEGINNINGS DAYCARE INC
not found ALLENDE RESTAURANT #2
not found BYRONS KITCHENS
not found AL MAIMANI FOOD
not found Seward
not found 7 ELEVEN #33726A
not found STARBUCKS COFFEE #2224
not found BENCHMARK HOSPITALITY OF CHICAGO, INC.
not found BOYA FOOD TRADING
not found BENCHMARK HOSPITALITY OF CHICAGO, INC.
not found CICERO & MONTROSE SHELL
not found nan
not found JEWEL FOOD STORE #3241
not found 7-ELEVEN #33496C
not found GOGO DOGS, LLC
not found WEST TOWER KITCHEN
not found nan
not found Burr
not found LOS OLIVO'S
not found FAT EDDIE'S EMPLOYEE CAFETERIA
not found nan
not found COCHIAROS PIZZA #2
not found nan
not found DIRKSEN US COURTHOUSE
not found DREAM'S MINI MART
not found OLOCUILTA #2 RESTAURANTE CENTROAMERICANO
not found PUBLICAN TAVERN K1 (T3 MAIN)
not found GENEVA
not found POLONIA

not found FINKI ELEMENTARY ACADEMY
not found WEN CIA CHINESE
not found FAMILY DOLLAR # 4666
not found SALAD WORKS (T1 C18 FOOD COURT)
not found IHOP # 1202
not found CHIPOTLE MEXICAN GRILL #2923
not found nan
not found BURKER KING #244
not found BURGER KING #25272
not found PANDA EXPRESS #1422
not found MAYFLOWER SEAFOOD RESTAURANT, LLC
not found BILLY GOAT (T1/C18 FOOD COURT)
not found NIKKI RAE'S FOOD TRUCK
not found DIRKSEN US COURTHOUSE
not found MARISCOS ESTILO RIO BALSAS
not found RADAIOS BROS FRANKSVILLE INC
not found DANIEL WEBSTER ELEMENTARY/LORRAINE HANSBERRY CPC
not found nan
not found Whistler
not found BACK OF THE YARDS
not found OLOCUILTA #2 RESTAURANTE CENTROAMERICANO
not found COCHIAROS PIZZA #2
not found STARBUCKS COFFEE #228
not found EL GALLO MEXICAN FOOD INC.
not found AFC SUSHI @ JEWEL OSCO #3082
not found JEWEL FOOD STORE #3082
not found EAST TOWER MAIN KITCHEN
not found PANERA BREAD #987
not found Snappy Convenience Center/Subway/Dunkin Donut
not found TAQUERIA LOS COMALES #1
not found DREAM'S MINI MART
not found FAT EDDIE'S EMPLOYEE CAFETERIA
not found SALAD WORKS (T1 C18 FOOD COURT)
not found OSCO DRUR # 3082
not found nan
not found FRUTERIA ANDY #2
not found PANDA EXPRESS #299
not found MAYFLOWER SEAFOOD RESTAURANT, LLC
not found FAMILY DOLLAR # 4666
not found Cooked Chicago
not found Snappy Convenience Center/Subway/Dunkin Donut
not found JEWEL FOOD STORE #3241
not found HO FAT LEE CHINESE KITCHEN
not found AFC SUSHI@JEWEL-OSCO #3241
not found OLOCUILTA #2 RESTAURANTE CENTROAMERICANO
not found ASHLAND WEST FALCON FUEL
not found LOBO REY
not found TAQUERIA LOS COMALES #1
not found 72ST SHELL
not found NO DENIAL FOODS
not found J + M GRILLE
not found Whistler
not found nan
not found Hanson Park
not found HAROLD'S CHICKEN  #71
not found Murray
not found MARKET PLACE/STARBUCKS COFFE/FRANGO/GODIVA
not found DALE VIDA A TU CUERPO
not found HAROLD'S CHICKEN SHACK #55
not found MARCO'S DRIVE INN
not found 72ST SHELL
not found nan
not found LOBO REY
not found DENNIS PIZZA GUZMAN
not found Haley, Alex  Mod.
not found STARBUCKS COFFEE # 2449
not found WALMART #5781
not found JEWEL FOOD STORE #3234
not found HERMOSA
not found STARBUCKS COFFEE #212
not found Sauganash
not found MANOLO'S TAMALES #3
not found Whistler
not found LITTLE CAESAR PIZZA #1648
not found FUSHING CO
not found Edgebrook
not found Hanson Park
not found PILSEN MODULAR
not found IDY'S CUBAN SANDWHICH
not found nan
not found PANDA EXPRESS RESTAURANT #2685
not found J + M GRILLE
not found LAZARO CARDENAS BRANCH
not found AFC SUSHI @JEWEL-OSCO #3345
not found NORTHDOWN
not found TANOR KOBOB INC.
not found INNOVATIVE CUISINE SERVICES
not found SALSA BORRACHA/MAMBO CLUB
not found nan
not found JOSEPH GARY SCHOOL/MODULAR/ANNEX
not found STARBUCKS COFFEE # 2449
not found BNL's PIZZA & POKE
not found Sauganash
not found nan
not found HERMOSA
not found David Jenson - Personal Chef, Ltd
not found BRIOCHE DOREE  (T3/G/ROTUNDA)
not found 72ST SHELL
not found DISCOUNT STOP INC.
not found STARBUCKS COFFEE #232
not found Walgreens #7559
not found CRAVE B2B, LLC
not found LA TORTA CHILANGA #2
not found AFC SUSHI@JEWEL OSCO #3470
not found Edgebrook
not found CICERO & NORTH FOOD & LIQUOR
not found JEWEL FOOD STORE #3470
not found CICERO & NORTH FOOD & LIQUOR
not found DONI DESSERT AND PASTRY
not found AFC SUSHI @JEWEL-OSCO #3345
not found JEWEL FOOD  STORE # 3345
not found SUBWAY 47512
not found FRUTERIA ANDY #2
not found LA TORTA CHILANGA #2
not found HERMOSA
not found BAR LORRAININE'S
not found HAROLDS #82
not found MANOLOS TAMALES, INC. #1
not found NORTHERN TRUST FOOD HALL

In [6]:
places_df.head()

,Data Name,Data License,Data Address,Data Lat,Data Lng,Google Name,User Rating,Total User Reviews,Google Address,Google Lat,Google lng
0,NECESSARY & SUFFICIENT COFFEE,2677227.0,3624 W WRIGHTWOOD AVE,41.928352,-87.718097,necessary & sufficient coffee,4.8,5,"3624 W Wrightwood Ave, Chicago, IL 60647, USA",41.928405,-87.718141
1,NECESSARY & SUFFICIENT COFFEE,2677227.0,3624 W WRIGHTWOOD AVE,41.928352,-87.718097,necessary exTRAVagance,0.0,0,"3624 W Wrightwood Ave, Chicago, IL 60647, USA",41.928405,-87.718141
2,SKY DINE 311,2670530.0,311 S WACKER DR,41.877792,-87.636524,311 South Wacker,4.3,141,"311 S Wacker Dr #1150, Chicago, IL 60606, USA",41.877445,-87.635652
3,I-CAFE SUKUR'S PLACE,2333622.0,1812-1814 W IRVING PARK RD,41.954318,-87.674760,I-Cafe Sukur's Place / Pide Ve Lahmacun,4.6,398,"1814 W Irving Park Rd, Chicago, IL 60613, USA",41.954391,-87.674759
4,LA CHAPARRITA,2689521.0,2300 S THROOP ST,41.850451,-87.658798,La Chaparrita,4.5,241,"2500 S Whipple St #4138, Chicago, IL 60623, USA",41.846260,-87.701709

In [7]:
#REVIEW: I have the condition set to greater than 0 which allows lat or lng to not equal, 
# but we can make it stricter by setting it = 2

# Create column that checks if lat and lngs are equal and drop rows that do not match dataset
places_df['drop_lat'] = np.where(round(places_df["Data Lat"],3)==round(places_df["Google Lat"],3), 1,0)
places_df['drop_lng'] = np.where(round(places_df["Data Lng"],3)==round(places_df["Google lng"],3), 1,0)
places_df['drop_latlng'] = np.where(places_df["drop_lat"] + places_df["drop_lng"] >0, 1,0)
places_df.head()

,Data Name,Data License,Data Address,Data Lat,Data Lng,Google Name,User Rating,Total User Reviews,Google Address,Google Lat,Google lng,drop_lat,drop_lng,drop_latlng
0,NECESSARY & SUFFICIENT COFFEE,2677227.0,3624 W WRIGHTWOOD AVE,41.928352,-87.718097,necessary & sufficient coffee,4.8,5,"3624 W Wrightwood Ave, Chicago, IL 60647, USA",41.928405,-87.718141,1,1,1
1,NECESSARY & SUFFICIENT COFFEE,2677227.0,3624 W WRIGHTWOOD AVE,41.928352,-87.718097,necessary exTRAVagance,0.0,0,"3624 W Wrightwood Ave, Chicago, IL 60647, USA",41.928405,-87.718141,1,1,1
2,SKY DINE 311,2670530.0,311 S WACKER DR,41.877792,-87.636524,311 South Wacker,4.3,141,"311 S Wacker Dr #1150, Chicago, IL 60606, USA",41.877445,-87.635652,0,0,0
3,I-CAFE SUKUR'S PLACE,2333622.0,1812-1814 W IRVING PARK RD,41.954318,-87.674760,I-Cafe Sukur's Place / Pide Ve Lahmacun,4.6,398,"1814 W Irving Park Rd, Chicago, IL 60613, USA",41.954391,-87.674759,1,1,1
4,LA CHAPARRITA,2689521.0,2300 S THROOP ST,41.850451,-87.658798,La Chaparrita,4.5,241,"2500 S Whipple St #4138, Chicago, IL 60623, USA",41.846260,-87.701709,0,0,0

In [8]:
places_df_2 = places_df[places_df['drop_latlng'] == 1]
places_df_2

,Data Name,Data License,Data Address,Data Lat,Data Lng,Google Name,User Rating,Total User Reviews,Google Address,Google Lat,Google lng,drop_lat,drop_lng,drop_latlng
0,NECESSARY & SUFFICIENT COFFEE,2677227.0,3624 W WRIGHTWOOD AVE,41.928352,-87.718097,necessary & sufficient coffee,4.8,5,"3624 W Wrightwood Ave, Chicago, IL 60647, USA",41.928405,-87.718141,1,1,1
1,NECESSARY & SUFFICIENT COFFEE,2677227.0,3624 W WRIGHTWOOD AVE,41.928352,-87.718097,necessary exTRAVagance,0.0,0,"3624 W Wrightwood Ave, Chicago, IL 60647, USA",41.928405,-87.718141,1,1,1
3,I-CAFE SUKUR'S PLACE,2333622.0,1812-1814 W IRVING PARK RD,41.954318,-87.674760,I-Cafe Sukur's Place / Pide Ve Lahmacun,4.6,398,"1814 W Irving Park Rd, Chicago, IL 60613, USA",41.954391,-87.674759,1,1,1
5,CONVENE,2665419.0,131 S DEARBORN ST,41.879885,-87.629212,Convene,4.6,22,"16 W Adams St, Chicago, IL 60603, USA",41.879507,-87.628346,1,0,1
6,CONVENE,2665419.0,131 S DEARBORN ST,41.879885,-87.629212,Urban Convene,0.0,0,"16 W Adams St, Chicago, IL 60603, USA",41.879507,-87.628346,1,0,1
7,CONVENE,2665419.0,131 S DEARBORN ST,41.879885,-87.629212,Convene,0.0,0,"16 W Adams St, Chicago, IL 60603, USA",41.879507,-87.628346,1,0,1
8,ALEXANDER'S,2684666.0,6158 N CLARK ST,41.994391,-87.670296,Alexander's Restaurant,4.6,374,"6158 N Clark St, Chicago, IL 60660, USA",41.994280,-87.670485,1,1,1
9,ALEXANDER'S,2684666.0,6158 N CLARK ST,41.994391,-87.670296,Alexander's Breakfast & Lunch,4.5,602,"6158 N Clark St, Chicago, IL 60660, USA",41.994280,-87.670485,1,1,1
56,EDWARDS (ANNEX),2040683.0,4815 S KARLOV,41.805523,-87.725819,Edwards Elementary School,3.8,25,"4815 S Karlov Ave, Chicago, IL 60632, USA",41.805376,-87.725536,0,1,1
57,ALEXANDER'S RESTAURANT,10916.0,6158 N CLARK ST,41.994391,-87.670296,Alexander's Restaurant,4.6,374,"6158 N Clark St, Chicago, IL 60660, USA",41.994280,-87.670485,1,1,1
58,ALEXANDER'S RESTAURANT,10916.0,6158 N CLARK ST,41.994391,-87.670296,J. Alexander's Restaurant,4.5,1113,"6158 N Clark St, Chicago, IL 60660, USA",41.994280,-87.670485,1,1,1
59,ALEXANDER'S RESTAURANT,10916.0,6158 N CLARK ST,41.994391,-87.670296,Alexander's Breakfast & Lunch,4.5,602,"6158 N Clark St, Chicago, IL 60660, USA",41.994280,-87.670485,1,1,1
60,ALEXANDER'S RESTAURANT,10916.0,6158 N CLARK ST,41.994391,-87.670296,Alexanders Restaurant,4.5,846,"6158 N Clark St, Chicago, IL 60660, USA",41.994280,-87.670485,1,1,1
84,Clissold,22761.0,2350 W 110 Pl (11032S),41.693054,-87.680862,Clissold Elementary School,2.3,17,"2350 W 110th Pl, Chicago, IL 60643, USA",41.693446,-87.680192,1,0,1
99,ALEXANDER'S,2684666.0,6158 N CLARK ST,41.994391,-87.670296,Alexander's Restaurant,4.6,374,"6158 N Clark St, Chicago, IL 60660, USA",41.994280,-87.670485,1,1,1
100,ALEXANDER'S,2684666.0,6158 N CLARK ST,41.994391,-87.670296,Alexander's Breakfast & Lunch,4.5,602,"6158 N Clark St, Chicago, IL 60660, USA",41.994280,-87.670485,1,1,1
101,"COYOTES RESTAURANT, INC.",2022125.0,1451 W 18TH ST,41.857731,-87.663356,Coyotes Restaurant,4.3,502,"1451 W 18th St, Chicago, IL 60608, USA",41.857703,-87.663411,1,1,1
104,SALSITA,2289529.0,3706 N HALSTED ST,41.949338,-87.649696,Salsita,4.5,162,"3706 N Halsted St, Chicago, IL 60613, USA",41.949429,-87.649827,1,1,1
105,KELLOGG ELEMENTARY SCHOOL,23971.0,9241 S Leavitt (2200W),41.725253,-87.677196,Kellogg Elementary School,4.9,10,"9241 S Leavitt St, Chicago, IL 60643, USA",41.725234,-87.676808,1,1,1
108,WHIZ KIDS NURSERY CENTER INC.,2215893.0,514-522 W 103RD ST,41.707113,-87.636204,Whiz Kids Nursery Center,5.0,6,"518 W 103rd St, Chicago, IL 60628, USA",41.707117,-87.636334,1,1,1
149,ZAMZAM BANQUET HALL,1493295.0,6755 W DIVERSEY AVE,41.930778,-87.795243,Zam Zam Banquet Hall,3.7,70,"2759 N Oak Park Ave, Chicago, IL 60707, USA",41.930747,-87.795106,1,1,1
171,ROOTS HANDMADE PIZZA - SECOND CITY/UTOPIAN TAI...,2689806.0,1610 N WELLS ST,41.911494,-87.634868,The Second City,4.6,1801,"1616 N Wells St, Chicago, IL 60614, USA",41.911607,-87.634996,0,1,1
172,ROOTS HANDMADE PIZZA - SECOND CITY/UTOPIAN TAI...,2689806.0,1610 N WELLS ST,41.911494,-87.634868,Roots Handmade Pizza,4.3,901,"1616 N Wells St, Chicago, IL 60614, USA",41.911607,-87.634996,0,1,1
173,ROOTS HANDMADE PIZZA - SECOND CITY/UTOPIAN TAI...,2689806.0,1610 N WELLS ST,41.911494,-87.634868,Utopian Tailgate,4.4,15,"1616 N Wells St, Chicago, IL 60614, USA",41.911607,-87.634996,0,1,1
180,PIZZERIA BRANDI,2496153.0,3170 S ASHLAND AVE,41.835749,-87.665842,Brandi Pizza & Wings,3.8,118,"3170 S Ashland Ave, Chicago, IL 60608, USA",41.835816,-87.666192,1,1,1
181,COOK ELEMENTARY SCHOOL,22801.0,8150 S Bishop (1432W),41.745263,-87.659812,Cook Elementary School,4.0,15,"8150 S Bishop St, Chicago, IL 60620, USA",41.745820,-87.659981,0,1,1
182,MAHALIA JACKSON ELEMENTARY SCHOOL,26651.0,917 W 88th St (8800S),41.734098,-87.646757,Mahalia Jackson Elementary School,3.5,4,"917 W 88th St, Chicago, IL 60620, USA",41.733846,-87.646957,1,1,1
224,KITSCH'N ON ROSCOE,68487.0,2005 W ROSCOE ST,41.943105,-87.678679,Kitsch'n on Roscoe,4.3,267,"2005 W Roscoe St, Chicago, IL 60618, USA",41.943005,-87.678787,1,1,1
251,ROWE-CLARK MATH & SCIENCE ACADEMY,2202622.0,3645 W CHICAGO AVE,41.895335,-87.718050,Rowe-Clark Math & Science Academy,3.8,35,"3645 W Chicago Ave, Chicago, IL 60651, USA",41.895322,-87.718335,1,1,1
252,CARNITAS Y SUPERMERCADO EL GIGANTE INC,1592986.0,2500 N LARAMIE AVE,41.926006,-87.756363,Carnitas Y Supermercado El Gigante,4.4,149,"2500 N Laramie Ave, Chicago, IL 60639, USA",41.926131,-87.756686,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54242,NATY'S PIZZA,1167763.0,5129 S KEDZIE AVE,41.799938,-87.703595,Naty's Pizza,3.7,395,"5129 S Kedzie Ave, Chicago, IL 60632, USA",41.799955,-87.703624,1,1,1
54243,NATY'S PIZZA,1167763.0,5129 S KEDZIE AVE,41.799938,-87.703595,Naty's Pizza,4.4,134,"5129 S Kedzie Ave, Chicago, IL 60632, USA",41.799955,-87.703624,1,1,1
54244,NATY'S PIZZA,1167763.0,5129 S KEDZIE AVE,41.799938,-87.703595,Naty's Pizza 26st,4.2,148,"5129 S Kedzie Ave, Chicago, IL 60632, USA",41.799955,-87.703624,1,1,1
54286,BUNCHES OF LOVE,2623023.0,62 W 111TH PL,41.691762,-87.625441,Bunches of Love Childcare LLC.,0.0,0,"62 W 111th Pl, Chicago, IL 60628, USA",41.691943,-87.625502,1,0,1
54287,ERNST PRUSSING ELEMENTARY SCHOOL,25031.0,4650 N Menard (5800W),41.965611,-87.772451,Prussing Elementary School,4.0,18,"4650 N Menard Ave, Chicago, IL 60630, USA",41.965646,-87.772743,1,0,1
54288,MIDDLE BROW,2609018.0,2002 N MOZART ST,41.917590,-87.698749,Bungalow by Middle Brow,4.6,197,"2840 W Armitage Ave, Chicago, IL 60647, USA",41.917768,-87.698880,1,1,1
54289,HEALTHCARE ALTERNATIVE SYSTEMS,23562.0,1949 N HUMBOLDT BLVD,41.917073,-87.701930,"Healthcare Alternative Systems, Inc.",4.0,10,"2755 W Armitage Ave, Chicago, IL 60647, USA",41.917240,-87.696790,1,0,1
54290,HEALTHCARE ALTERNATIVE SYSTEMS,23562.0,1949 N HUMBOLDT BLVD,41.917073,-87.701930,Healthcare Alternative Systems,4.0,4,"2755 W Armitage Ave, Chicago, IL 60647, USA",41.917240,-87.696790,1,0,1
54291,HEALTHCARE ALTERNATIVE SYSTEMS,23562.0,1949 N HUMBOLDT BLVD,41.917073,-87.701930,Healthcare Alternative Systems,4.4,22,"2755 W Armitage Ave, Chicago, IL 60647, USA",41.917240,-87.696790,1,0,1
54292,HEALTHCARE ALTERNATIVE SYSTEMS,23562.0,1949 N HUMBOLDT BLVD,41.917073,-87.701930,Healthcare Alternative Systems,5.0,2,"2755 W Armitage Ave, Chicago, IL 60647, USA",41.917240,-87.696790,1,0,1
54293,HEALTHCARE ALTERNATIVE SYSTEMS,23562.0,1949 N HUMBOLDT BLVD,41.917073,-87.701930,Healthcare Alternative Systems Inc,5.0,1,"2755 W Armitage Ave, Chicago, IL 60647, USA",41.917240,-87.696790,1,0,1
54294,JAMMY BURGER,2637358.0,7301 S KEDZIE AVE,41.760806,-87.702517,Jammy Burger,4.6,16,"7301 S Kedzie Ave, Chicago, IL 60629, USA",41.760624,-87.702270,1,0,1
54297,The Dark Horse Tap and Grill,1144544.0,3443 N SHEFFIELD AVE,41.944837,-87.654110,Dark Horse Tap & Grille,4.3,249,"3443 N Sheffield Ave, Chicago, IL 60657, USA",41.944854,-87.653910,1,1,1
54318,BLUE SKY BAKERY & CAFE,2036397.0,3720 N LINCOLN AVE,41.949357,-87.675581,Blue Sky Bakery,4.4,63,"3720 N Lincoln Ave, Chicago, IL 60613, USA",41.949238,-87.675642,1,1,1
54319,Hash,2198209.0,1357 N WESTERN AVE,41.906521,-87.686973,Hash Chicago,4.5,422,"1357 N Western Ave, Chicago, IL 60622, USA",41.906534,-87.686833,1,1,1
54320,Hash,2198209.0,1357 N WESTERN AVE,41.906521,-87.686973,Dispensary 33,4.6,123,"1357 N Western Ave, Chicago, IL 60622, USA",41.906534,-87.686833,1,1,1
54321,Hash,2198209.0,1357 N WESTERN AVE,41.906521,-87.686973,Hashbrowns Cafe,4.2,304,"1357 N Western Ave, Chicago, IL 60622, USA",41.906534,-87.686833,1,1,1
54322,Hash,2198209.0,1357 N WESTERN AVE,41.906521,-87.686973,Hashbrowns,4.2,355,"1357 N Western Ave, Chicago, IL 60622, USA",41.906534,-87.686833,1,1,1
54324,RENALDI'S PIZZA,2252464.0,2827-2831 N BROADWAY,41.933536,-87.644543,Renaldi's Pizza,4.2,446,"2827 N Broadway, Chicago, IL 60657, USA",41.933631,-87.644297,1,0,1
54325,COMMUNITY FOOD MART,2510877.0,600 E 103RD ST,41.707500,-87.608823,Community Food Mart and Restaurant,5.0,4,"600 E 103rd St, Chicago, IL 60628, USA",41.707536,-87.608760,1,1,1
54326,AVONDALE COFFEE AND GRILL HOUSE,2368771.0,3634 W BELMONT AVE,41.939308,-87.718735,The Avondale Tap,4.6,239,"3634 W Belmont Ave, Chicago, IL 60618, USA",41.939376,-87.718775,1,1,1
54327,MAGGIE GYROS & CHICKEN,1869774.0,349 E 47TH ST,41.809257,-87.617666,Maggie Gyros & Chicken,3.9,252,"349 E 47th St, Chicago, IL 60653, USA",41.809173,-87.617587,1,1,1
54328,MAGGIE GYROS & CHICKEN,1869774.0,349 E 47TH ST,41.809257,-87.617666,Maggie Gyros & Philly Inc,3.9,131,"349 E 47th St, Chicago, IL 60653, USA",41.809173,-87.617587,1,1,1
54349,MR. POLLO,2542966.0,3026 W BELMONT AVE,41.939467,-87.703811,Mr. Pollo,4.5,213,"3026 W Belmont, Chicago, IL 60618, USA",41.939521,-87.703816,0,1,1
54350,MR. POLLO,2542966.0,3026 W BELMONT AVE,41.939467,-87.703811,Mr Pollo,4.3,157,"3026 W Belmont, Chicago, IL 60618, USA",41.939521,-87.703816,0,1,1
54352,CHINA PALACE,2476335.0,1129 W THORNDALE AVE,41.989925,-87.659440,China Palace,3.6,99,"1129 W Thorndale Ave, Chicago, IL 60660, USA",41.989670,-87.659387,1,1,1
54353,TWO MILE COFEE BAR,2641611.0,1766 W 95TH ST,41.721260,-87.667257,Two Mile Coffee Bar,4.7,12,"1766 W 95th St, Chicago, IL 60643, USA",41.721368,-87.667318,1,1,1
54354,CARMELO'S TACO PLACE,2617376.0,2746 W 59TH ST,41.786528,-87.693030,Carmelo's Taco Place,3.9,33,"2746 W 59th St, Chicago, IL 60629, United States",41.786584,-87.692944,1,1,1
54360,EL LLANO RESTAURANT,2583790.0,3941 N LINCOLN AVE,41.953509,-87.678140,El Llano Restaurant,4.6,49,"3941 N Lincoln Ave, Chicago, IL 60613, USA",41.953503,-87.678036,1,1,1
54361,EL LLANO RESTAURANT,2583790.0,3941 N LINCOLN AVE,41.953509,-87.678140,Brasa Roja Elston,4.4,258,"3941 N Lincoln Ave, Chicago, IL 60613, USA",41.953503,-87.678036,1,1,1

In [9]:
#Develop Data Frame ot the Ratings Summary by City and Interest

#Groupby License Number
places_count_df = places_df.groupby(['Data License'])

#Summary Calculations
average_ratings = round(places_count_df['User Rating'].mean(),2)
average_reviews = round(places_count_df['Total User Reviews'].mean(),2)
total_reviews = places_count_df['Total User Reviews'].sum()
count_places = places_count_df['User Rating'].count()

In [10]:
#Final Data Frame
#Match on Data License for Final Merge with City of Chicago Data
google_reviews = pd.DataFrame({'Average of Ratings': average_ratings,
                              'Average Number of Reviews': average_reviews, 
                              'Total Number of Reviews': total_reviews,
                              'Total Returned': count_places,})

google_reviews["Data License"] = google_reviews.index.get_level_values(0)
# google_reviews["interest_sort"] = google_reviews.index.get_level_values(1)

google_reviews.head(20)

,Average of Ratings,Average Number of Reviews,Total Number of Reviews,Total Returned,Data License
Data License,,,,,
0.0,3.92,40.22,4907,122,0.0
149.0,4.20,376.00,752,2,149.0
164.0,3.97,167.67,1509,9,164.0
257.0,4.50,909.00,909,1,257.0
404.0,4.30,264.00,528,2,404.0
429.0,4.80,364.00,364,1,429.0
491.0,4.40,441.00,882,2,491.0
691.0,2.67,48.67,146,3,691.0
692.0,4.00,73.00,73,1,692.0
783.0,4.50,109.00,218,2,783.0
800.0,4.40,196.00,392,2,800.0
853.0,4.30,1257.00,1257,1,853.0
955.0,1.83,8.15,163,20,955.0
990.0,4.25,537.00,1074,2,990.0
1043.0,4.80,26.00,52,2,1043.0
1050.0,4.50,131.00,262,2,1050.0
1052.0,3.60,11.00,22,2,1052.0
1058.0,3.97,346.21,4847,14,1058.0
1060.0,4.40,19.00,19,1,1060.0
1094.0,4.10,790.00,790,1,1094.0

In [11]:
#**REVIEW**:  20 is the max return from the api call, so i randomly picked 10 as an option to drop on
# seemed like if 20 were being returned, then it is not likely to be the same place under different names

google_reviews = google_reviews[google_reviews['Total Returned'] < 10]
google_reviews

,Average of Ratings,Average Number of Reviews,Total Number of Reviews,Total Returned,Data License
Data License,,,,,
149.0,4.20,376.00,752,2,149.0
164.0,3.97,167.67,1509,9,164.0
257.0,4.50,909.00,909,1,257.0
404.0,4.30,264.00,528,2,404.0
429.0,4.80,364.00,364,1,429.0
491.0,4.40,441.00,882,2,491.0
691.0,2.67,48.67,146,3,691.0
692.0,4.00,73.00,73,1,692.0
783.0,4.50,109.00,218,2,783.0
800.0,4.40,196.00,392,2,800.0
853.0,4.30,1257.00,1257,1,853.0
990.0,4.25,537.00,1074,2,990.0
1043.0,4.80,26.00,52,2,1043.0
1050.0,4.50,131.00,262,2,1050.0
1052.0,3.60,11.00,22,2,1052.0
1060.0,4.40,19.00,19,1,1060.0
1094.0,4.10,790.00,790,1,1094.0
1168.0,4.20,437.00,437,1,1168.0
1196.0,4.30,619.00,1238,2,1196.0
1206.0,4.20,35.00,35,1,1206.0
1212.0,4.40,242.00,242,1,1212.0
1219.0,4.30,736.00,736,1,1219.0
1237.0,4.20,58.00,116,2,1237.0
1254.0,4.40,450.00,450,1,1254.0
1311.0,4.10,258.38,2067,8,1311.0
1315.0,4.10,258.38,2067,8,1315.0
1387.0,4.00,30.00,30,1,1387.0
1425.0,4.30,378.00,378,1,1425.0
1434.0,3.70,78.00,156,2,1434.0
1470.0,4.40,325.00,975,3,1470.0
...,...,...,...,...,...
3619531.0,4.20,165.00,165,1,3619531.0
3624677.0,4.70,7.00,7,1,3624677.0
3624741.0,4.50,16.00,16,1,3624741.0
3624785.0,2.25,5.00,10,2,3624785.0
3634641.0,3.70,3.00,3,1,3634641.0
3638635.0,3.30,7.00,7,1,3638635.0
3639288.0,4.10,29.00,58,2,3639288.0
3675788.0,3.30,4.00,4,1,3675788.0
3676367.0,5.00,3.00,3,1,3676367.0
3676560.0,4.30,16.00,16,1,3676560.0
3676607.0,3.70,17.00,17,1,3676607.0
3708710.0,3.87,26.50,159,6,3708710.0
3708731.0,3.10,7.00,7,1,3708731.0
3708781.0,3.10,21.00,21,1,3708781.0
3708791.0,3.20,19.00,19,1,3708791.0
3708792.0,4.30,7.00,14,2,3708792.0
3708811.0,3.90,12.00,12,1,3708811.0
3708845.0,3.50,15.00,30,2,3708845.0
3709480.0,4.20,14.00,14,1,3709480.0
3759848.0,3.90,23.00,23,1,3759848.0
3759896.0,3.60,14.00,42,3,3759896.0
3759928.0,3.30,13.00,13,1,3759928.0
3760050.0,3.70,6.00,6,1,3760050.0
3760459.0,3.20,14.00,14,1,3760459.0
3760532.0,4.40,9.00,9,1,3760532.0
3760620.0,5.00,2.00,4,2,3760620.0
3808690.0,3.45,26.33,158,6,3808690.0
3808691.0,4.50,8.00,24,3,3808691.0
3808890.0,1.00,1.00,1,1,3808890.0
3846027.0,4.60,8.00,16,2,3846027.0

In [13]:
#Write Final Dataset to CSV
google_reviews.to_csv("google_reviews.csv", index=False, header=True)